repos:
  - repo: https://github.com/best-doctor/pre-commit-hooks
    rev: v1.0.11
    hooks:
      - id: package-structure
        name: Root packages structure
        entry: validate_package_structure
        language: python

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id: black
        exclude: \.py-tpl$

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.18.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==24.4.2
        files: 'docs/.*\.txt$'
        args: ["--rst-literal-block"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.7.0
    hooks:
      - id: eslint

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        args: [--strict, --disallow-untyped-calls, --disallow-untyped-defs, --disallow-incomplete-defs,--disallow-subclassing-any, --ignore-missing-imports, --follow-imports=silent]
        additional_dependencies: [django-stubs, types-PyYAML,pytest,hypothesis,types-commonmark,urllib3,hypothesmith]
