repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id: black
        exclude: \.py-tpl$

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.18.0
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==24.4.2
        files: 'docs/.*\.txt$'
        args: ["--rst-literal-block"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.7.0
    hooks:
      - id: eslint

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        exclude: ^(docs/conf.py|scripts/generate_schema.py)$
        additional_dependencies:
          - django-stubs  # Add Django type hints
          - types-PyYAML
          - tomli >= 0.2.6, < 2.0.0
          - click >= 8.1.0, != 8.1.4, != 8.1.5
          - packaging >= 22.0
          - platformdirs >= 2.1.0
          - pytest
          - hypothesis
          - aiohttp >= 3.7.4
          - types-commonmark
          - urllib3
          - hypothesmith
        args:
          - --strict
          - --disallow-untyped-calls
          - --disallow-untyped-defs
          - --disallow-incomplete-defs
          - --disallow-subclassing-any
          - --ignore-missing-imports
          - --follow-imports=silent

      - id: mypy
        name: mypy (Python 3.10)
        files: scripts/generate_schema.py
        args: [ "--python-version=3.10" ]
        additional_dependencies:
          - django-stubs
          - types-PyYAML
          - tomli >= 0.2.6, < 2.0.0
          - click >= 8.1.0, != 8.1.4, != 8.1.5
          - packaging >= 22.0
          - platformdirs >= 2.1.0
          - pytest
          - hypothesis
          - aiohttp >= 3.7.4
          - types-commonmark
          - urllib3
          - hypothesmith
