repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    args: [--strict]
    hooks:
      - id: black
        exclude: \.py-tpl$

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.18.0
    args: [--strict]
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - black==24.4.2
        files: 'docs/.*\.txt$'
        args: ["--rst-literal-block"]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    args: [--strict]
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.7.0
    hooks:
      - id: eslint

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        args:
          - --strict
          - --disallow-untyped-calls
          - --disallow-untyped-defs
          - --disallow-incomplete-defs
          - --disallow-subclassing-any
          - --ignore-missing-imports
          - --follow-imports=silent
        additional_dependencies:
          - django-stubs
          - types-PyYAML
          - pytest
          - hypothesis
          - types-commonmark
          - urllib3
          - hypothesmith

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-yaml
        args: [ '--unsafe' ]
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: no-commit-to-branch
        args: [ '--branch=development','--branch=prod' ]
      - id: check-json
      - id: pretty-format-json
      - id: check-added-large-files
      - id: flake8
        args: ['--max-line-length=100', '--ignore=E203 E266 E501 W503', '--select=F', '--extend-ignore=F401']
