repos:
-   repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    - id: black
      additional_dependencies: ['click==8.0.4']
      args: [--line-length=100]
      language_version: python3

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.1
  hooks:
    - id: mypy
      args:
        - --strict
        - --disallow-untyped-calls
        - --disallow-untyped-defs
        - --disallow-incomplete-defs
        - --disallow-subclassing-any
        - --ignore-missing-imports
        - --follow-imports=silent
      additional_dependencies:
        - django-stubs
        - types-PyYAML
        - pytest
        - hypothesis
        - types-commonmark
        - urllib3
        - hypothesmith

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3 # Possible releases: https://github.com/hadialqattan/pycln/releases
    hooks:
      - id: pycln
        args: [ --config=pyproject.toml ]

-   repo: https://github.com/best-doctor/pre-commit-hooks
    rev: v1.0.11
    hooks:
      - id: package-structure
        name: Root packages structure
        entry: validate_package_structure
        language: python

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-yaml
      args: ['--unsafe']
    - id: detect-private-key
    - id: forbid-new-submodules
    - id: no-commit-to-branch
      args: ['--branch=development','--branch=prod']
    - id: check-json
    - id: pretty-format-json
    - id: check-added-large-files
    - id: flake8
      args: [--max-line-length=100, --ignore=E203 E266 E501 W503]
